# Generated by Django 2.2.4 on 2019-08-16 15:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_resume_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_completed',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
