# Generated by Django 2.2.4 on 2019-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20190816_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='github',
            field=models.CharField(blank=True, help_text='https://github.com/[User_ID]', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='linked_in',
            field=models.CharField(blank=True, help_text='https://www.linkedin.com/in/[User_ID]', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='stack_overflow',
            field=models.CharField(blank=True, help_text='https://stackoverflow.com/users/[User_ID]', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='telegram',
            field=models.CharField(blank=True, help_text='https://t.me/[User_ID]', max_length=100, null=True),
        ),
    ]
