# Generated by Django 2.2.4 on 2019-08-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20190824_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_completed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
